import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useSupabaseClient, useUser } from '@supabase/auth-helpers-react'
import { useEffect } from 'react'
import Navbar from '../components/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const supabaseClient = useSupabaseClient()
  const user = useUser()

  return (
    <>
      <Head>
        <title>BPHC Cab Sharing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{/* <Navbar current="home" /> */}</main>
    </>
  )
}
